# NUMPY

### Arrays- Structured list of Numbers

Vectors(1-D array), matrix(2-D,3-D array), Images(array of pixels value), Tensors(Combination of matrices value), convnets

In [37]:
import numpy as np
d=[[1,2,3,4],[5,6,7,8]]
print(d)
print(type(d))
#convert d into an array with rows and columns
arr = np.array(d)
print(arr)
print(type(arr))

[[1, 2, 3, 4], [5, 6, 7, 8]]
<class 'list'>
[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [2]:
#This tells us the size of array in the form of - (rows,columns)
dimension=arr.shape
# No. of rows
rows=arr.shape[0]
#No. of columns
columns=arr.shape[1]
#No of channels
#channels= arr.shape[2]  -- applicable only when 3d matrix is there. for e.g - colourful image(RGB is a 3 dimensional matrix) 
#Length of array
tot=len(arr)
print("Dimension: ",dimension)
print("Rows: ",rows)
print("Columns: ",columns)
#print("Channels: ",channels)
print("Length: ",tot)


Dimension:  (2, 4)
Rows:  2
Columns:  4
Length:  2


In [3]:
#datatype
print(arr.dtype)

int32


In [4]:
#creating an array with all elements zero
arr2 = np.zeros((3,6))  # with 3 rows and 6 Columns
print(arr2)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [5]:
#creating an array with elements ranging from 0 to n-1
arr3 = np.arange(10)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
##creating an array with all elements one
z=np.ones((2,5))
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
##creating an identity matrix
z=np.eye(5,5)
z

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
# creating a array with all values 'v'
v = 89
z=np.full((3,3),v)  # creates a 3x3 matrix with all values as v 
z

array([[89, 89, 89],
       [89, 89, 89],
       [89, 89, 89]])

In [9]:
# creating an array with same dimension as z but with all values 1
z1=np.ones_like(z)  # Thus, as dimension of z is 3x3, z1 will be a 3x3 matrix with all entries 1
print(z1)
# Similarly zeros_like(z) will create a matrix with all values 0
z2=np.zeros_like(z)
print(z2)


[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [10]:
# creating array with random values
z=np.random.rand(5,3)
print(z)

[[0.74643431 0.71002042 0.67719732]
 [0.22304139 0.68259609 0.27216034]
 [0.90730328 0.35941384 0.3744247 ]
 [0.17858991 0.71641657 0.6704685 ]
 [0.34989429 0.86210942 0.93489585]]


#### Array -  Slicing

In [11]:
#printing the array elements from index 5 to 7
arr=[1,2,3,4,6,910,6,7,90,7]
arr[5:8]

[910, 6, 7]

In [12]:
#2-d array
arr=np.array([[1,2,3,4],[5,6,3,7],[7,8,10,6]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  3,  7],
       [ 7,  8, 10,  6]])

In [13]:
# 2-d array slicing:
b=arr[1:3,:2]  # Elements of row from: index 1 to 2 and elements of columns from: Starting(0) to 1
b

array([[5, 6],
       [7, 8]])

In [14]:
# Making changes in b
b[0][0]=0
b

array([[0, 6],
       [7, 8]])

In [15]:
# Change in b will lead to change in arr
arr

array([[ 1,  2,  3,  4],
       [ 0,  6,  3,  7],
       [ 7,  8, 10,  6]])

Thus, arr[1][0] changed from 5 t0 0.

So, if any changes are made in the array formed by slicing of another array, the original array is also changed.

In [16]:
#changing the elements from index a to b to some other value
arr3 = np.arange(10)
arr3[5:8]=12
arr3

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [17]:
ss = np.array([[arr3[1],arr3[2],arr3[3]]])
ss[0]=3
arr3

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

This doesnt make any change in arr3 i.e arr3[1] which is ss[0] is still the same. 

Thus the original array is altered only if the new array is formed by slicing, not otherwise.

# Reshape, transpose & Sign

In [18]:
#reshaping the array-deciding the number of rows and columns of an array
re_arr= np.arange(10).reshape(2,5)
print(re_arr)


[[0 1 2 3 4]
 [5 6 7 8 9]]


In [19]:
#printing the array from second row(index =1)
re_arr[1:]

array([[5, 6, 7, 8, 9]])

In [20]:
# Transposing the array --> Interchange rows and columns
re_arr.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [21]:
#Tells the sign of the array elements
arr = np.array([[1,-3,4],[-6,7,0]])
np.sign(arr)  # 1 for positive, -1 for negative and 0 for 0


array([[ 1, -1,  1],
       [-1,  1,  0]])

## Universal functions

In [22]:
arr = np.array([[1,3,4],[6,7,8]])
#1) Evaluate square root of all the elements
print(np.sqrt(arr))
arr2 =np.sqrt(arr)

[[1.         1.73205081 2.        ]
 [2.44948974 2.64575131 2.82842712]]


In [23]:
#2) floor - returns the greatest integer smaller than the number
 #   ceil - returns the smallest integer greater than the number
#   e.g - 3 <3.4 < 4  --> 3 is floor(3.4) and 4 is ceil(3.4)
print(np.floor(arr2))
print('\n')
print(np.ceil(arr2))

[[1. 1. 2.]
 [2. 2. 2.]]


[[1. 2. 2.]
 [3. 3. 3.]]


In [24]:
#3)rounding off the elements
print(np.round(arr2))

[[1. 2. 2.]
 [2. 3. 3.]]


In [25]:
#4) log of all elements
print(np.log(arr2))

[[0.         0.54930614 0.69314718]
 [0.89587973 0.97295507 1.03972077]]


## Binary Functions

In [26]:
a = np.array([4,3,2])
b=  np.array([3,6,7])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b)) #reminder

[7 9 9]
[ 1 -3 -5]
[12 18 14]
[1.33333333 0.5        0.28571429]
[1 3 2]


In [27]:
# Dot product and multiply
# Multiply : multiplies each element of array a with other array b
a = np.array([4,3,2])
b=  np.array([[3],[6],[7]])
print("Multiply: " ,np.multiply(a,b))
# Dot product performs row to column matriux multiplication
print("Dot: ",a.dot(b))

Multiply:  [[12  9  6]
 [24 18 12]
 [28 21 14]]
Dot:  [44]


## Logical Functions

In [28]:
print(a)
print(b)
print(np.greater(a,b))
print(np.less(a,b))
print(np.greater_equal(a,b))
print(np.equal(a,b))

[4 3 2]
[[3]
 [6]
 [7]]
[[ True False False]
 [False False False]
 [False False False]]
[[False False  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True False]
 [False False False]
 [False False False]]
[[False  True False]
 [False False False]
 [False False False]]


## Statistics Functions

In [29]:
arr = np.array([[1,2,3],[3,2,5],[5,2,6]])
print(np.mean(arr))  # finds average of all elements
print(np.std(arr))  # finds standard deviation of all elements
print(np.var(arr))  #finds variance of all elements



3.2222222222222223
1.617802197617893
2.617283950617284


## Append 

In [30]:
#axis =0 : appends the arrays row wise i.e rows of second array will be appended below first array
a= np.array([[1,2,3],[3,2,5]])
b= np.array([[5,26,32],[1,8,9]])
np.append(a,b,axis=0)


array([[ 1,  2,  3],
       [ 3,  2,  5],
       [ 5, 26, 32],
       [ 1,  8,  9]])

In [31]:
#axis =1 : appends the arrays column wise i.e rows of second array will be appended to the right of first array
a= np.array([[1,2,3],[3,2,5]])
b= np.array([[5,26,32],[1,8,9]])
np.append(a,b,axis=1)

array([[ 1,  2,  3,  5, 26, 32],
       [ 3,  2,  5,  1,  8,  9]])

# Broadcasting

Passing arguments of 1 variable to other.

In [32]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
v=np.array([[1,0,1]])
v

array([[1, 0, 1]])

We want to add elements of vector v to every row of vector x: and form y

In [34]:
y=np.empty_like(x)
for i in range(len(x)):
    y[i,:] = x[i,:]+v[:]
y   

array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10]])

# Combining Arrays

1)Vertical Stack -

Combines array vertically i.e places the second array below first array.

The two arrays should have same no of columns.

In [35]:
a1=np.array([[1,2,3]])
a2=np.array([[9,22,36]])
np.vstack((a1,a2))

array([[ 1,  2,  3],
       [ 9, 22, 36]])

2) Horizontal stack-

Combines array horizontally i.e places the second array to the right of first array.

In [36]:
a1=np.array([[1,2,3]])
a2=np.array([[9,22,36]])
np.hstack((a1,a2))

array([[ 1,  2,  3,  9, 22, 36]])